name: syntax
on: push

jobs:
  tester:
    name: USO Test
    runs-on: ubuntu-latest

    steps:
      - name: Serban Andrei | Copiaza repository-ul
        uses: actions/checkout@v2
      
      - name: Compileaza codul
        run: gcc src/add.c -o add

      - name: Ruleaza teste
        run: | 
         test1=./add 1 2
         test2=./add 10 5
         test3=./add 50 50
         test4=./add 1 99
         test5=./add 1 1
         test test1 -eq 3
         test test2 -eq 15
         test test3 -eq 100
         test test4 -eq 100
         test test5 -eq 2
